### PR TITLE
Add mouseEntered/mouseExited events

### PR DESCRIPTION
**Pull request by mattfelsen**
As per discussion in https://github.com/openframeworks/openFrameworks/pull/3162

### CODE REVIEW

**Comment by mattfelsen** [comment]
Oh geez, this is insane. It's all the changes to openframeworks/master since you branched off ~6mo again. Did I do this wrong // is there something I should do differently?

**Comment by danoli3** [comment]
Hey @mattfelsen, I saw this, just chiming in as I seem subscribed to bakers repo. 

Best thing probably is to get @bakercp to update to latest from his end first, then PR in.
Else you can get your patch directly by adding .patch to the commit hash:
https://github.com/mattfelsen/openFrameworks/commit/59301b9829947a8edb13fbbb7a9c31e9b2be70fc.patch

So you could checkout @bakercp branch directly, then apply the patch with SourceTree or Git (download the patch file and save as .patch). Then PR the changes (which will only be your new changes) XD

**Comment by bakercp** [comment]
Yeah, I need to update this branch -- it's way behind.  I should be able to do that in the next day or two ... keep an eye here @mattfelsen and thanks @danoli3

**Comment by mattfelsen** [comment]
Should I just submit a new PR to openframeworks/master (I branched from here today for my mouseEnteredExited branch)? Seems like it'd be less hassle, no?

**Comment by bakercp** [comment]
If it doesn't depend on anything in my branch, then it probably makes more sense to do it directly.

**Comment by mattfelsen** [comment]
Yea, no use trying to resolve the merge conflicts for the pre-multiwindow code just to change it again. Ok, submitted a new PR then.

**Pull request closed without merging**
